### ISSUE TITLE
Adding Apache 2.0 licence to Blitz

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/blitz#148]
Blitz is currently MIT licensed, rather than following the rust ecosystem standard of being dual-licensed under MIT and Apache 2.0 licences. This is somewhat academic as Blitz has dependencies which are solely MIT licensed (e.g. Taffy) and event some which are MPL licensed (e.g. Stylo). Nevertheless, I would like to bring Blitz itself onto the standard dual license if possible. To do this we will need the permission of everyone who has contributed to Blitz so far. Luckily that's a relatively small list:

- [x] @nicoburns
- [x] @jkelleyrtp
- [x] @matthunz
- [x] @cfraz89
- [x] @kokoISnoTarget
- [x] @DavidHusicka
- [x] @luoxiaozero
- [x] @mrgzi
- [x] @sepcnt

If you are tagged above, and you are willing to licence your contributions to Blitz under an Apache 2.0 license in addition to the existing MIT license, please could you comment below saying so (I'm not anticipating that this will be a problem for anyone, but in case you're not willing, then that would also be useful to know).

**Comment by DavidHusicka** [comment]
Not a problem for me. You have ok here 👍🏻

**Comment by mrgzi** [comment]
It's okay for me 👍 I even forgot what I contributed :D

**Comment by kokoISnoTarget** [comment]
Works for me.

**Comment by cfraz89** [comment]
Fine with me

**Comment by luoxiaozero** [comment]
Fine with me.

**Comment by sepcnt** [comment]
Fine with me.

**Comment by matthunz** [comment]
All good with me!
