### ISSUE TITLE
How to debug broken page?

### ISSUE THREAD

**Issue by nerdachse** [DioxusLabs/blitz#165]
Hey there!

First off: Thanks for this awesome project!

Now I am running it on hackernews and I get:

> ERROR: Unexpected token
> ERROR: Unexpected token

originating here: https://github.com/DioxusLabs/blitz/blob/main/packages/blitz-html/src/html_sink.rs#L199

Now the question is: How do I get to find out, what token is unexpected? How do you debug sites to find out, what's missing to get them working correctly?

To elaborate: Meanwhile I know about Alt+D, Alt+H and Alt+T... I am more interested in the general approach though.

**Comment by nicoburns** [comment]
So my approach is generally a mix of:
- ALT+D, ALT+H, ALT+T
- Adding `println` and `dbg` statements to the code (Blitz code, but also Taffy code)
- Trying to reduce the input while still triggering the bug to narrow down on what is causing the issue
- Opening the HTML in Chrome or another browser to see how that behaves (and perhaps modifying the html/css slightly)

I'm planning to add devtools similar to what other browsers have at some point. Which should hopefully be a game changer for debugging.

Does that answer your question?

**Comment by nerdachse** [comment]
Absolutely. thanks for taking the time to answer!
