### ISSUE TITLE
Follow links

### ISSUE THREAD

**Issue by nerdachse** [DioxusLabs/blitz#170]
I've started working on this feature "following links" in my local fork a couple of weeks back to get myself a bit familiar with the code base.

I simply added a bit of event handling on every layer to be able to change the current document.

Overall, while my solution does work, it feels (and is) hacky.

Have you thought about this already?

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add proper link handling to allow navigation between documents when clicking links. This involves changes to the Document, BlitzApplication, and DioxusNativeApplication structs to manage multiple documents and handle navigation events.

You can review changes in this commit: https://github.com/kkpo4553/DioxusLabs-blitz-170/commit/e9092b2a4ef695225fecfa2df08a42fdc1d06813.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by nicoburns** [comment]
@nerdachse I have. My plan is/was:

- `Document`s default action for links is to generate a new Winit UserEvent `BlitzEvent::Navigate(url)` or similar.
- Shell then receives event and triggers an http request for the new URL
- When that returns it does something similar to the [reload code in the `readme` app](https://github.com/DioxusLabs/blitz/blob/main/apps/readme/src/readme_application.rs#L51) (creates a new document and then replaces the document in the window with that new document).

To be worked out:
- How to handle the transitional/loading state:
   - Perhaps the new document should be created immediately (blank) and the populated when http request returns?
   - Perhaps there should be an intermediary "loading" document displaying some static HTML?
   - Do network requests for the old document need to be cleaned up? (probably get away with not in the short-term)
   - What happens on failure? (perhaps an "error" document displaying some static HTML?)

Long-term I would like to use "nested documents" (feature not implemented yet) to implement a browser UI using a `DioxusDocument` with the pages being nested `HtmlDocument`s. At that point the outer document could handle both the request lifecycle and loading/error UI.

I would be interested to see what you have come up with and if it is similar to the above.

**Comment by nicoburns** [comment]
I should add that the other thing we will want for "complete" link following is the ability to click on inline spans. Currently only block elements (including inline-block) are clickable. Some links are block/inline-block, but many are inline and those ones won't currently work. This work needs to happen in Parley.

**Comment by nicoburns** [comment]
> The other thing we will want for "complete" link following is the ability to click on inline spans. Currently only block elements (including inline-block) are clickable. Some links are block/inline-block, but many are inline and those ones won't currently work. This work needs to happen in Parley.

This has now been implemented. So it's just the actual document loading that needs to be implemented now.

**Comment by nerdachse** [comment]
Hey, wow, thanks for taking your time to answer in such a nice and fleshed out fashion!

Well, my idea was rougher, but similar, because it seems natural. It was just a hack, I replaces the whole document "brute force style", because I just wanted to get something useful (for me) going while exploring the codebase.

**Comment by nerdachse** [comment]
Adding the Event is easy enough.

Firing it inside `document`'s `handle_event` method not so much.

Either we make `handle_event` return an Optional Event (yet another enum?!) or we pass in a way to send the event over the proxy.
