### ISSUE TITLE
Problems with installing the package

### ISSUE THREAD

**Issue by mehranj73** [DioxusLabs/blitz#171]
How can I add this cargo yo my code? What packages do I need to run the examples you provided?

**Comment by nicoburns** [comment]
For a dioxus app based on Blitz you need `dioxus` and `dioxus-native` (see the [counter example](https://github.com/DioxusLabs/blitz/tree/main/examples/counter)). For rendering HTML or a URL you need `blitz-shell` (see the `url` or `screenshot` examples, or the `readme` app)
