### ISSUE TITLE
Focus Outline Color Different Based On Example Choice

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/blitz#33]
**Problem**

The outline color for the focus is red in the css_grid_buttons, but black in the buttons example:

**Steps To Reproduce**

- Run `cargo run --example buttons`, type tab a few times to move the focus
- Run `cargo run --example css_grid_buttons`, type tab a few times to move the focus

- **Expected behavior**

The outline color should be the same in both examples

**Screenshots**

buttons:
![image](https://github.com/DioxusLabs/blitz/assets/66571940/fd68746b-f299-4811-b248-e6ccd646dc93)
grid:
![image](https://github.com/DioxusLabs/blitz/assets/66571940/4a68c486-24e7-4acd-ad20-64b485e75094)

**Environment:**

- Renderer version: `Blitz master`
- Rust version: 1.43.0
- OS info: Windows 11

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by nicoburns** [comment]
This is no longer relevant to the new Blitz
