### ISSUE TITLE
Integrate Cosmic Text

### ISSUE THREAD

**Issue by ealmloff** [DioxusLabs/blitz#34]
## Specific Demand

[Cosmic text](https://github.com/pop-os/cosmic-text) implements some more advanced text layout and editing. It supports rendering bold, italicized, and multiline text. It also implements text editing on Unicode characters.

## Implement Suggestion

Replace the current text layout engine with Cosmic text and use Cosmic text to implement editing when input widgets are implemented.

Related: https://github.com/linebender/vello/issues/306

**Comment by jackpot51** [comment]
Are there issues with cosmic-text blocking this?

**Comment by jackpot51** [comment]
Thanks for the feedback. I'll be looking into layout with custom rectangles soon.
