### ISSUE TITLE
(Question) Does it will have a CLI tool beyond examples?

### ISSUE THREAD

**Issue by hardBSDk** [DioxusLabs/blitz#84]

**Comment by matthunz** [comment]
The [Dioxus CLI](https://crates.io/crates/dioxus-cli) should [soon](https://github.com/DioxusLabs/blitz/pull/67) work with Blitz so you can run `dx serve --platform desktop` and your app will automatically hot-reload

**Comment by hardBSDk** [comment]
@matthunz I'm aware of the Dioxus CLI, thanks!
