### ISSUE TITLE
Support web fonts (`@font-face`)

### ISSUE THREAD

**Issue by nicoburns** [DioxusLabs/blitz#91]
Many websites use web fonts. We should support them.

### Implementation Plan

- When (just after) a stylesheet is added to the `Stylist` we should introspect the stylesheet to look for @font-face rules
- We should fetch any font URLs found (for now this can be synchronous as with our other networking)
- If the font is successfully fetched then it should be registered with the Parley `FontContext` using https://docs.rs/fontique/0.1.0/fontique/struct.Collection.html#method.register_fonts . For now this can not worry about supporting custom names, matching criteria or deregistering.

**Comment by kokoISnoTarget** [comment]
I believe this can be closed.
