### ISSUE TITLE
Focus system

### ISSUE THREAD

**Issue by matthunz** [DioxusLabs/blitz#92]
IIRC we can port the `dioxus-desktop` [focus system](https://github.com/DioxusLabs/dioxus/blob/e1ea213d056d22dcc801a68b0f24300d32b0c90d/packages/desktop/src/element.rs#L101C8-L127) here . I'm not sure I understand that focus stack yet, but I believe we can port that method to Blitz's `Node` struct.

**Comment by nicoburns** [comment]
You could also look at legacy blitz's focus system (https://github.com/DioxusLabs/blitz/tree/legacy). Although I have no idea how good it is/was. Not sure if you'll be doing keyboard focus management, but if you are, I reckon we'll definitely want to support `tabindex="0"`, but we could potentially skip on non-zero tabindex to begin with.
