### ISSUE TITLE
Checkbox element

### ISSUE THREAD

**Issue by matthunz** [DioxusLabs/blitz#94]
Should we support `input { type: "checkbox" }` by displaying a default input widget?

I think the big question here is what should the default styling look like :eyes: I'm thinking now we might want to match browser implementations somewhat close, but we may have some creative freedom here.

One idea I had is re-using  the `masonry` [Checkbox](https://docs.rs/masonry/latest/masonry/widget/struct.Checkbox.html) widget here

**Comment by nicoburns** [comment]
Read-only checkboxes would also be useful for rendering checkbox lists in Github READMEs. Our markdown library already supports generating them. Perhaps the most expedient path forwards would be to implement this custom but use the Masonry Checkbox's paint implementation (which is of course vello-based anyway).

**Comment by nicoburns** [comment]
Closed by #125
